version: '3'
services: 
  bot:
    container_name: roger-bot
    build: .
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
    expose: 
      - '27017'
    volumes: 
      - "mongobot:/data/db"

volumes: 
  mongobot: